services:

  sveltekit-app:
    container_name: sveltekit-static-template
    image: sveltekit-static
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"