name: "Building"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.13"
          cache: "npm"

      - name: Install modules
        run: npm ci

      - name: Build frontend
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: npm run build
