name: "Preview"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}/preview/pr-${{ github.event.number }}"
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview
          path: build

  deploy_preview:
    needs: build_preview
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Download preview artifact
        uses: actions/download-artifact@v4
        with:
          name: preview
          path: preview/pr-${{ github.event.number }}

      - name: Upload combined artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const previewUrl = `${{ steps.deployment.outputs.page_url }}preview/pr-${{ github.event.number }}/`;
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: context.issue.number,
              body: `🚀 Github Pages Preview: ${previewUrl}`
            });
