name: "Github Pages preview"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.number }}"
        run: npm run build

      - name: Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
